name: Docker Build

on:
  push:
    branches:
      - main  # Adjust this to your default branch
    paths:
      - 'backend/src/**'
  pull_request:
    branches:
      - main  # Adjust this to your default branch
    paths:
      - 'backend/src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/bazel-public/bazel:8.0.0
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # - name: Configure Bazel
      #   run: echo "build --sandbox_fake_username=nonroot" >> .bazelrc

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          cd backend
          # Run bazel as non-root user
          useradd -m bazel_user
          chown -R bazel_user .
          su bazel_user -c "make build-docker"
          make push-docker
