name: Docker Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          cd backend
          sudo useradd -m bazel_user
          # Create build directory with proper permissions
          sudo mkdir -p /home/runner/work/dnd-ai/dnd-ai/backend/build
          # Give bazel_user ownership of the entire project directory
          sudo chown -R bazel_user:bazel_user /home/runner/work/dnd-ai
          # Run the build as bazel_user
          sudo -u bazel_user make build-docker
          # Restore ownership to runner user for docker commands
          sudo chown -R $USER:$USER /home/runner/work/dnd-ai
          # Run docker commands as current user
          make push-docker
