name: Docker Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          cd backend
          sudo mkdir -p build
          sudo chown -R $(id -u):$(id -g) .
          make build-docker
          make push-docker

      # Add Google Cloud authentication
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_KEYS }}

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: dnd-ai
          region: us-east1 # Your region
          image: ashwinmahesh1/dnd-ai:${{ github.sha }}
